# Generated by Django 4.0.1 on 2022-01-11 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_requestion_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestion',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
